// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKGX9QhnqFQC-l4ARkA0dDBTadmRBRTUw',
    appId: '1:770364003586:web:877496a330a37f08ad1e1b',
    messagingSenderId: '770364003586',
    projectId: 'mvvm-consepts',
    authDomain: 'mvvm-consepts.firebaseapp.com',
    storageBucket: 'mvvm-consepts.firebasestorage.app',
    measurementId: 'G-ZN87V4WCP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGGpflUKe1iG8JbVkAX6Jl_k7dXeTMK4',
    appId: '1:770364003586:android:7c42337559292f56ad1e1b',
    messagingSenderId: '770364003586',
    projectId: 'mvvm-consepts',
    storageBucket: 'mvvm-consepts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyDee5gxy4WR8JcTIVHAhPkthA2FKFA9A',
    appId: '1:770364003586:ios:2f8513d2418b9376ad1e1b',
    messagingSenderId: '770364003586',
    projectId: 'mvvm-consepts',
    storageBucket: 'mvvm-consepts.firebasestorage.app',
    iosBundleId: 'com.example.mvvmConsepts',
  );
}
